Promise.reject("test").catch((x) => console.log('rejected', x));